# Generated by Django 3.0.5 on 2020-04-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200410_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('OutDoor', 'OutDoor')], max_length=200, null=True),
        ),
    ]
